name: Docker Build and Deploy

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print application.properties
      run: echo "${{ secrets.ENV_FRONT }}" > frontend/.env.development
    - name: Display application.properties
      run: cat backend/src/main/resources/application.properties

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t osephsm060429/frontend:v1 .

    - name: Push Docker image to Docker Hub
      run: docker push osephsm060429/frontend:v1

    - name: SSH into AWS and update container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/frontend
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
